% This file is part of LCToolbox.
% (c) Copyright 2018 - MECO Research Team, KU Leuven. 
%
% LCToolbox is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published 
% by the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% LCToolbox is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
% 
% You should have received a copy of the GNU Lesser General Public License
% along with LCToolbox. If not, see <http://www.gnu.org/licenses/>.

classdef IdentFRDmod < FRDmod
    %IDENTFRDMOD FRDmod generated by nonpar_ident
    %   FRDmod containing extra info regarding the identification process
    %   
    
    properties (Access=public)
        G_          % structure containing all model properties
        U_          % structure containing all properties of input fourier coeffs
        Y_          % structure containing all properties of output fourier coeffs
        CYU_        % sturcture containing all convariance properties of CUY
    end
    
    methods
        function self = IdentFRDmod(varargin)
            self@FRDmod(varargin{:});
        end
    end
end

